language: java
services:
  - mysql
before_install:
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
  - mysql -uroot -e "CREATE DATABASE examshelper"
  - mysql -uroot -e "CREATE DATABASE examshelper_test"
  - cp .travis.test.properties src/test/resources/test.properties
  - cp .travis.settings.xml $HOME/.m2/settings.xml
